### ISSUE TITLE
how should http-hash-routers be nested?

### ISSUE THREAD

**Issue by nrw** [Matt-Esch/http-hash-router#4]
this issue is probably related: https://github.com/Matt-Esch/http-hash/issues/1

**Comment by Raynos** [comment]
By design this doesn't support nesting. We did nesting in production and we regretted the indirection of multiple routing layers.

I recommend you do something like

``` js
// endpoints/users
module.exports = {
  '/user/search': fn,
  '/user/comment': fn
};

// endpoints/admin
module.exports = {
  '/admin/users': fn
};

// router.js
var hash = HashRouter();

var user = require('./endpoints/user');
var admin = require('./endpoints/admin');

hash.set('/user/search', user['/user/search']);
hash.set('/user/comment', user['/user/comment']);
hash.set('/admin/users/', admin['/admin/users']);

module.exports = hash;
```

**Comment by nrw** [comment]
Was the indirection just harder to debug? I'm hoping to learn from your experience.

**Comment by Raynos** [comment]
@nrw there were problems with the indirection
- routing was done twice, performance hit
- routing was done twice, there are two places that know about "handlers" building an id for a handler was hard because each handler had two ids
- doing meta programming at the top level router was hard because it does not have access to real handlers
- we had a bunch of unneeded helper functions that created the inner routers, this made debugging harder as well
- having an endpoint return an object of urls is 10x simpler then having it return a function. 
- there were no benefits to nested routing that we could find.

**Comment by nrw** [comment]
@Raynos thanks for the detailed answer! i've repeatedly encountered 2 and 4.
